id: P004213
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1210
  title: ནག་པོ་པའི་བསྒྲུབ་ཐབས་བསྒོམ་འབུམ
  author: ''
  volumes:
    715165a0c0d54ea5936e3c8e3e77af22:
      image_group_id: I1CZ2073
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
