id: I75399A67
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:57:26+00:00'
last_modified: '2022-06-07T21:07:15.642363+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1210
  title: ནག་པོ་པའི་བསྒྲུབ་ཐབས་བསྒོམ་འབུམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F117:
      image_group_id: I1CZ2073
      title: ''
      total_pages: 66
      order: 1
      base_file: F117.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
